export const GET_CHOCOLATE_BRAND = "GET_CHOCOLATE_BRAND";
export const GET_CHOCOLATE_BRAND_SUCCESS = " GET_CHOCOLATE_BRAND_SUCCESS";
export const GET_CHOCOLATE_BRAND_FAILURE ="GET_CHOCOLATE_BRAND_FAILURE";