export const GET_CHOCOLATE_BRAND = 'GET_CHOCOLATE_BRAND';
export const GET_CHOCOLATE_BRAND_SUCCESS = 'GET_CHOCOLATE_BRAND_SUCCESS';
export const GET_CHOCOLATE_BRAND_FAILURE = 'GET_CHOCOLATE_BRAND_FAILURE';

export const GET_BRAND_ITEM = 'GET_BRAND_ITEM';
export const GET_BRAND_ITEM_SUCCESS = 'GET_BRAND_ITEM_SUCCESS';
export const GET_BRAND_ITEM_FAILURE = 'GET_BRAND_ITEM_FAILURE';

export const GET_BRAND_DETAILS = 'GET_BRAND_DETAILS';
export const GET_BRAND_DETAILS_SUCCESS = 'GET_BRAND_DETAILS_SUCCESS';
export const GET_BRAND_DETAILS_FAILURE = 'GET_BRAND_DETAILS_FAILURE';
