export const GET_CHOCOLATE = "GET_CHOCOLATE";
export const GET_CHOCOLATE_SUCCESS = "GET_CHOCOLATE_SUCCESS";
export const GET_CHOCOLATE_FAILURE = "GET_CHOCOLATE_FAILURE";

export const GET_CHOCOLATE_ITEM= "GET_CHOCOLATE_ITEM"
export const GET_CHOCOLATE_ITEM_SUCCESS = "GET_CHOCOLATE_ITEM_SUCCESS"
export const GET_CHOCOLATE_ITEM_FAILURE = "GET_CHOCOLATE_ITEM_FAILURE"


export const GET_CHOCOLATE_DETAILS ="GET_CHOCOLATE_DETAILS";
export const GET_CHOCOLATE_DETAILS_SUCCESS="GET_CHOCOLATE_DETAILS_SUCCESS";
export const GET_CHOCOLATE_DETAILS_FAILURE ="GET_CHOCOLATE_DETAILS_FAILURE";
